logging:
  level:
    org.springframework: INFO
    ma.gov.pfe: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/user-db-${spring.profiles.active}-${server.port}
    username: sa
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}-${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: "*" 
  endpoint:
    health:
      show-details: always
